// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// CLI commands (migrate, studio, introspect) connect directly here.
// Runtime queries go through the driver adapter in src/lib/db.ts instead,
// which uses the pooled DATABASE_URL. Migrations use the unpooled DIRECT_URL
// to avoid issues with pgbouncer + prepared statements on Neon.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
